# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine
WORKDIR /app

# install dependencies and build
COPY package.json tsconfig.json tsup.config.ts .
COPY src ./src
RUN npm install --ignore-scripts && npm run build && npm prune --production

CMD ["node", "dist/index.js"]
